[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Functions to encode/decode and encrypt/decrypt data using public-key, authenticated encryption."
documentation = "http://maidsafe.net/secure_serialisation/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "secure_serialisation"
readme = "README.md"
repository = "https://github.com/maidsafe/secure_serialisation"
version = "0.2.0"

[dependencies]
clippy = {version = "~0.0.44", optional = true}
maidsafe_utilities = "~0.2.1"
rustc-serialize = "~0.3.18"
sodiumoxide = "~0.0.9"

[dev-dependencies]
rand = "~0.3.14"
